# Typus Roles Configuration File
#
# Use the README file as a reference to customize settings.

admin:
  AdminEvent: create, read, update, delete
  Comment: create, read, update, delete
  Event: create, read, update, delete
  RollBook: create, read, update, delete
  User: create, read, update, delete
